# To generate an HTML from this spec with redoc-cli
# Run `npx @redocly/cli build-docs -o sketchySoundsAPI.html api-specification.yaml`
######################################################################################
#    Specification is also available at https://kremling.de/sketchySoundsAPI.html    #
######################################################################################
openapi: 3.0.0
info:
  title: SketchySounds API
  description: API to generate musical scores from uploaded sketches
  version: "0.0.1"
  contact:
    email: kremlingph95027@th-nuernberg.de

servers:
  - url: http://localhost:4242
    description: Local server

paths:
  /healthcheck:
    get:
      summary: Health Check of the API
      responses:
        '200':
          description: API is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: up

  /upload:
    post:
      summary: Uploads an image for processing
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                inputFile:
                  type: string
                  format: binary
      responses:
        '200':
          description: Image received and processing started
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bild empfangen
                  transaction_id:
                    type: string
                    example: 00000000-0000-0000-0000-000000000000
        '400':
          description: No input file sent or format could not be determined
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Keine Eingabedatei gesendet"
        '404':
          description: No input file found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Die Eingabedatei wurde nicht gefunden"
        '413':
          description: File size exceeds 20MB
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Bilddateigröße überschreitet 20 MB"

  /upload-dall-e:
    post:
      summary: Uploads an image for processing with DALL-E model
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                inputFile:
                  type: string
                  format: binary
      responses:
        '200':
          description: Image received and processing started
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bild empfangen
                  transaction_id:
                    type: string
                    example: 00000000-0000-0000-0000-000000000000
        '400':
          description: No input file sent or format could not be determined
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Keine Eingabedatei gesendet"
        '404':
          description: No input file found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Die Eingabedatei wurde nicht gefunden"
        '413':
          description: File size exceeds 20MB
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Bilddateigröße überschreitet 20 MB"

  /analysis/{transaction_id}:
    get:
      summary: Retrieves analysis for a given transaction
      parameters:
        - in: path
          name: transaction_id
          required: true
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Analysis of the image
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: string
                    example: 00000000-0000-0000-0000-000000000000
                  analysis:
                    type: array
                    items:
                      type: string
                    description: List of attributes detected in the sketch
                    example:
                    - hoch
                    - laut
        '204':
          description: No content available yet for this transaction
        '404':
          description: Transaction ID not found or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaktion nicht gefunden oder ungültig"
        '409':
          description: Transaction in error state
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaktion fehlgeschlagen, bitte Fehler-Endpunkt verwenden"

  /analysis-intern/{transaction_id}:
    get:
      summary: Retrieves internal analysis (full text) for a given transaction
      parameters:
        - in: path
          name: transaction_id
          required: true
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Analysis of the image
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: string
                    example: 00000000-0000-0000-0000-000000000000
                  analysis:
                    type: string
                    description: Full text description of the sketch
                    example: "Gelbe Sonne (oben links): geschwungen, abstrakt; Blaues Haus (Mitte): tief;"
        '204':
          description: No content available yet for this transaction
        '404':
          description: Transaction ID not found or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaktion nicht gefunden oder ungültig"
        '409':
          description: Transaction in error state
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaktion fehlgeschlagen, bitte Fehler-Endpunkt verwenden"

  /score/{transaction_id}:
    get:
      summary: Retrieves musical score for a given transaction
      parameters:
        - in: path
          name: transaction_id
          required: true
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Generated musical score
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        '204':
          description: No content available yet for this transaction
        '404':
          description: Transaction ID not found or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaktion nicht gefunden oder ungültig"
        '409':
          description: Transaction in error state
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaktion fehlgeschlagen, bitte Fehler-Endpunkt verwenden"

  /last-score:
    get:
      summary: Retrieves the last generated musical score
      responses:
        '200':
          description: Last generated musical score returned
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        '404':
          description: No last transaction found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Die letzte Transaktion wurde nicht gefunden"

  /status/{transaction_id}:
    get:
      summary: Retrieves status of a given transaction
      parameters:
        - in: path
          name: transaction_id
          required: true
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Status of the transaction
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: string
                    example: 00000000-0000-0000-0000-000000000000
                  status:
                    type: string
                    enum: [Success, Error, Running analysis, Running generation, Received, Idling]
                    example: Success
        '404':
          description: Transaction ID not found or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaktion nicht gefunden oder ungültig"

  /error/{transaction_id}:
    get:
      summary: Retrieves error information for a given transaction
      parameters:
        - in: path
          name: transaction_id
          required: true
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Error information on the transaction
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: string
                    example: 00000000-0000-0000-0000-000000000000
                  error:
                    type: string
                    example: OpenAI denied the request. Maybe unallowed content?
        '404':
          description: Transaction ID not found or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Transaktion nicht gefunden oder ungültig"
        '409':
          description: Transaction is not in error state
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Diese Transaktion hat keine Fehler"

  /music/{transaction_id}:
    get:
      summary: Retrieves generated music for a given transaction
      parameters:
        - in: path
          name: transaction_id
          required: true
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Generated music
          content:
            audio/wav:
              schema:
                type: string
                format: binary
        '204':
          description: No music content available yet for this transaction
        '404':
          description: Transaction ID not found or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaktion nicht gefunden oder ungültig"
        '409':
          description: Transaction in error state while generating music
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaktion fehlgeschlagen, bitte Fehler-Endpunkt verwenden"